version: "3.4"

services:
  ip2country:
    image: "nexus-ng.themarker.com/ip2country:${version:-latest}"
    hostname: ip2counrty
    networks:
      - prod02
    ports:
      - "4005:8080"
networks:
  prod02:
    external: true
